# Generated by Django 2.2.3 on 2019-07-22 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Request ID')),
                ('sender', models.CharField(max_length=128)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=30)),
                ('complaint', models.TextField(verbose_name='Complaint')),
                ('status', models.IntegerField(choices=[(0, 'Pending Service'), (1, 'Serviced')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
