# Generated by Django 2.2.3 on 2019-07-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mech_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='sender',
        ),
    ]
