# Generated by Django 2.2.3 on 2019-07-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mech_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceRequests',
            new_name='ServiceRequest',
        ),
    ]
