# Generated by Django 2.2.3 on 2019-07-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mech_app', '0003_auto_20190730_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='departments',
            field=models.TextField(default='[Mechanical, Process]', verbose_name='Department'),
        ),
    ]
