# Generated by Django 2.2.3 on 2019-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mech_app', '0004_servicerequest_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Ongoing'), (2, 'Completed')], default=0),
        ),
    ]
