# Generated by Django 2.2.3 on 2019-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('request_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Request ID')),
                ('sender', models.CharField(max_length=128)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=64)),
                ('complaint', models.TextField(verbose_name='Complaint')),
            ],
        ),
    ]
